SELECT WAREHOUSE_ID, WAREHOUSE_NAME, ADDRESS, IFNULL(FREEZER_YN, 'N') AS "FREEZER_YN"
FROM FOOD_WAREHOUSE
WHERE ADDRESS LIKE "경기도%"
ORDER BY WAREHOUSE_ID
-- ID, 이름, 주소, 냉동시설 여부 조회
-- NULL인경우 N (냉동시설)
-- 창고 ID 기준 오름차순 정렬