-- 코드를 입력하세요
SELECT T1.TITLE, T1.BOARD_ID, T2.REPLY_ID, T2.WRITER_ID, T2.CONTENTS, SUBSTR(T2.CREATED_DATE,1,10) AS "CREATED_DATE"
FROM USED_GOODS_BOARD T1
JOIN USED_GOODS_REPLY T2 ON T1.BOARD_ID = T2.BOARD_ID 
WHERE T1.CREATED_DATE LIKE "2022-10%"
ORDER BY T2.CREATED_DATE, T1.TITLE
-- BOARD_ID가 FK
-- BOARD와 REPLY 테이블에서 2022년 10월에 작성된 게시글 제목, 게시글 ID, 댓글 ID, 댓글 작성자 ID, 댓글 내용, 댓글 작성일 조회
-- 댓글 작성일 기준 오름차순, 게시글 제목 기준 오름차순 
-- CREATED_DATE 포맷조심하기